#!/bin/sh

progname=$(basename "$0")

usage() {
	echo "Usage: $progname FILE"
	exit 1
}

[ -z $1 ] && usage
if [ -z $BROWSER ]; then
	BROWSER=vimb
fi

tmpfile=$(mktemp)
lowdown -s $1 > $tmpfile
$BROWSER $tmpfile
rm $tmpfile
