#!/bin/sh
# Rename a file according to a sed command.

renamefile() {
	path="$1"

	dirname=$(dirname "$path")
	filename=$(basename "$path")
	newname=$(echo "$filename" | sed "$pattern")

	if [ "$newname" != "$filename" ]; then
		mv "$path" "$dirname"/"$newname"
	fi
}


progname=$(basename "$0")

if [ $# -lt 2 ]; then
	echo "Usage: $progname PATTERN FILE [FILE...]" 1>&2
	exit 1
fi

pattern="$1"
shift

for file in "$@"; do
	if [ ! -e "$file" ]; then
		echo "$progname: '$file': No such file or directory" 1>&2
		continue
	fi
	renamefile "$file"
done
